### ISSUE TITLE
Callback when dialog dismissed

### ISSUE THREAD

**Issue by buttim** [AppDevNext/ChangeLog#195]
Apparently there is no way of knowing when the dialog has been closed. This is vital if you need to show another dialog at startup or for example a showcase/tutorial.

**Comment by hannesa2** [comment]
Here you go https://github.com/AppDevNext/ChangeLog/releases/tag/3.6

**Comment by buttim** [comment]
That was FAST! Thank you so much. You've encouraged me to open another issue, LOL!
