### ISSUE TITLE
Dialog flickering (continuos vertical resize)

### ISSUE THREAD

**Issue by buttim** [AppDevNext/ChangeLog#204]
I added the sample code from the README to my app, using more or less the same changelog_master.xml resource.
The result is that the changelog dialog appears but does a continuous vertical resize as in the video attached

https://github.com/user-attachments/assets/4846510b-9444-430c-ac08-fd7942779d0a

**Comment by hannesa2** [comment]
It opens a `AlertDialog` `.show()`
<img width="578" alt="image" src="https://github.com/user-attachments/assets/057f1928-d168-42d8-a2cc-418d67f582cb">

I'm not sure, what you do on your side. Because only you know the source code, you have to solve this.
And please don't send some code spinets, this makes no sense.
Only a **running** sample makes sense

**Comment by buttim** [comment]
Yes I'm aware of the AlertDialog, I checked the code. And I know  this won't help you that much in solving the problem. Still wanted to let you know so if somebody else finds the same problem this issue might help him if we ever find a solution. Obviously  it does not make much sense to send you the whole app source and it could be quite hard to build a minimal example.

**Comment by hannesa2** [comment]
> it could be quite hard to build a minimal example.

But you have more experience to make such a code 😁
Please Imagine, for me it's much more harder to prepare it

**Comment by buttim** [comment]
Sure. I wasn't asking to do that. I know you can't do much here, I just thought it might help to have the problem documented. Still working on it without much luck. I do have other (smaller) AlertDialogs opening on the same Activity with no problem. It might be related to the size of the specific content, since none of mine have a WebView inside. I tried to "inflate" one of my AlertDialogs but it did behave well. I will report any finding

**Comment by buttim** [comment]
I think I nailed it. When the user presses the "MORE..." button you're opening a second alert before the first one gets actually dismissed. This seems to generate a race condition at least on my Android version/brand/phone. I solved it by changing the line in which the "full dialog" is shown like this (this also requires to `import android.os.Handler` and `import android.os.Looper`):
```
        if (!full) {
            // Show "More…" button if we're only displaying a partial change log.
            builder.setNegativeButton(
                R.string.changelog_show_full
            ) { _, _ -> Handler(Looper.getMainLooper()).post{fullLogDialog.show()} }
        }
```
If you require it I will open a PR, but I think it should be simpler to just copy/paste the line. Let me know

**Comment by hannesa2** [comment]
You this flickers on your side ?

https://github.com/user-attachments/assets/0c9d49e0-0262-4623-9206-6f174d3af266

and you solved it for you with this ?

```
if (!full) {
            // Show "More…" button if we're only displaying a partial change log.
            builder.setNegativeButton(
                R.string.changelog_show_full
            ) { _, _ -> Handler(Looper.getMainLooper()).post{fullLogDialog.show()} }
        }

```

**Comment by buttim** [comment]
Nope. Still working in my app. I'm pretty sure in the example I would find no problem

**Comment by hannesa2** [comment]
Please give it a try https://github.com/AppDevNext/ChangeLog/releases/tag/3.7

**Comment by hannesa2** [comment]
3.7.1 only fixes jitpack.io publish
